version: '3.5'

services:

  froundend:
    build: ./frontend/ml-kurkkumopo-frontend/
    ports:
      - "3000:3000"
    
  backend:
    build: ./backend/ml-kurkkumopo-backend/
    ports:
      - "5000:5000"
    volumes:
      - ./model:/src/model  

  training: 
    build: ./training/ml-kurkkumopo-training/
    volumes:
      - ./model:/src/model 
      - ./imgs:/src/imgs



