version: '3.5'

services:

  frontend:
    build: ~/Documents/DevOps_with_Docker/Docker_exe/part1/part1.5
    ports:
      - "5000:5000"

  backend:
    build: ~/Documents/DevOps_with_Docker/Docker_exe/part1/part1.6
    ports:
       - "8000:8000"
    environment:
       - REDIS=redis
       - DB_USERNAME=postgres
       - DB_PASSWORD=postgres
       - DB_HOST=db
    

  redis:
    image: "redis:alpine"
   
  db:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
  